### ISSUE TITLE
decoding missing hash array initialization

### ISSUE THREAD

**Issue by Buhek23** [mathpn/py-qoi#6]
below line 231 missing hash array initialization.

line for px in hash_array:
        px.update(bytearray((0, 0, 0, 0)))

it's a problem when decoding images with transparent background.
When not initialized:
![not_initialized](https://user-images.githubusercontent.com/132842850/236694320-6062d6a5-1460-4e92-be42-4ac9f28c957a.png)
When initialized:
![initialized](https://user-images.githubusercontent.com/132842850/236694318-db1d3607-0f9c-40de-9016-a13a813ac8a7.png)

**Comment by mathpn** [comment]
Thank you for pointing this issue. It's now fixed.
