### ISSUE TITLE
Not using QOI_OP_DIFF and QOI_OP_LUMA  when possible

### ISSUE THREAD

**Issue by Buhek23** [mathpn/py-qoi#8]
When encoding not implemented wraparound operation, as described by documentation.
![image](https://github.com/mathpn/py-qoi/assets/132842850/4e9baab6-4336-4646-9772-fc214cfd4bbc)
![image](https://github.com/mathpn/py-qoi/assets/132842850/81f47920-21a1-493e-9ba4-0b6ea5d5dcbe)
Here is my solution for the problem as a function.
![image](https://github.com/mathpn/py-qoi/assets/132842850/b0ef09d4-715c-41a2-bf65-444f2dfed24f)
And usage of function in program.
![image](https://github.com/mathpn/py-qoi/assets/132842850/6c12e3b0-e08e-4748-bb55-ac6628304d03)
When encoding pictures like this it saves some space.
![bw](https://github.com/mathpn/py-qoi/assets/132842850/94f61fde-98c3-4b9e-a455-9b5f0d399703)

**Comment by mathpn** [comment]
thank you for pointing this out, you'll see I've opted for a simpler implementation of wraparound (check here: https://github.com/mathpn/py-qoi/pull/9)

**Comment by Buhek23** [comment]
Hi,
I have checked the code and it doesn't seem right, what is now implemented is basically just to get a positive integer from 0 to 255.
But we need also a negative integer for color differences. Wraparount works like it is described on the picture below:
![image](https://github.com/mathpn/py-qoi/assets/132842850/6d0d3335-9a03-48fc-b068-277881341abf)
And if you think about it that means that diff -128 is equal to 128, so the minimum diff is always somewhere between this 2 numbers, an describes all of 256 possible differences.
I hope that this helps.

**Comment by mathpn** [comment]
Indeed, even though encoding and decoding still worked, it was not consistent with the original C implementation, which uses signed chars to store those values.

[Here](https://stackoverflow.com/questions/451375/what-does-it-mean-for-a-char-to-be-signed) is a quick discussion about signed char behavior. I've changed the wraparound operation to be consistent with the reference implementation: https://github.com/mathpn/py-qoi/pull/10

Also, there's another tiny change: https://github.com/mathpn/py-qoi/pull/11 - with this one the encoded files are now exactly identical to the ones produced by the reference QOI encoder.
